#!/bin/sh

[ $(pamixer --get-mute) = true ] && echo 婢 && exit

vol="$(pamixer --get-volume)"

if [ "$vol" -gt "80" ]; then
    icon=" "
elif [ "$vol" -gt "40" ]; then
    icon="墳 "
elif [ "$vol" -gt "15" ]; then
    icon="奔 "
elif [ "$vol" -gt "0" ]; then
    icon="奄 "
else
    echo 婢 && exit
fi

echo "$icon$vol%"
